<a href="https://colab.research.google.com/github/alifele/Neuro_Science/blob/master/Techniques_with_Bias_and_Variance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning Techniques with Bias and Variance Curve

in this note book i am going to implement some machine learning techniques to classify our neuron networks in 4 different classes

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import requests
import io
from tempfile import TemporaryFile


# Importing Data

the data that I am using throght out this note book are the ones that their features has reduced to 16 under PCA method (you can find additional information and relevant notebook on the repository of the project)

In [2]:
!pip install -q xlrd
!git clone https://github.com/alifele/Neuro_Science.git
!ls Neuro_Science
data = np.load('Neuro_Science/DataSet_with_Label.npz')

Cloning into 'Neuro_Science'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 39 (delta 11), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (39/39), done.
Data.npy		Neuro_PCA.ipynb
DataSet_with_Label.npz	README.md
IF_data.npz		Techniques_with_Bias_and_Variance.ipynb


In [3]:
print(data.files)
DataSet = data['DataSet']
Label = data['Label']
print(DataSet.shape)
print(Label.shape)

['DataSet', 'Label']
(160, 16)
(160,)


# Data Preparation

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(DataSet, Label, shuffle=True)

# Implementing Machine Learning Classification Algorithms

In [0]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

# * Support Vector Machine Classifier

In [6]:
svc_clf = SVC()
svc_clf.fit(X_train,Y_train)
print("The accurace of the SVM classifier is: {}".format( svc_clf.score(X_test,Y_test) ) )
# print("The coeeficients of the best fit are: {} and the intercept is:{} ".format( svc_clf.coef_, svc_clf.intercept_ ) )

The accurace of the SVM classifier is: 1.0


/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Cofusion Matrix

In [11]:
Y_predict_SVM = svc_clf.predict(X_test)
cnfmatrix_SVM = confusion_matrix(Y_test,Y_predict_SVM)
print(cnfmatrix_SVM)

[[14  0  0  0]
 [ 0  8  0  0]
 [ 0  0  9  0]
 [ 0  0  0  9]]


# * K Nearst Neigbors Classifier

In [13]:
knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train,Y_train)
print("The accuracy of the knn classifier is: {}".format( knn_clf.score(X_test,Y_test) ) )

The accuracy of the knn classifier is: 1.0


Confusion matrix

In [14]:
Y_predict_KNN = knn_clf.predict(X_test)
cnfmatrix_KNN = confusion_matrix(Y_test,Y_predict_KNN)
print(cnfmatrix_KNN)

[[14  0  0  0]
 [ 0  8  0  0]
 [ 0  0  9  0]
 [ 0  0  0  9]]



# * Decision Tree

In [16]:
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train,Y_train)
print("The accuracy of the tree classifier is: {}".format( tree_clf.score(X_test,Y_test) ) )


The accuracy of the tree classifier is: 1.0


Confusion matrix

In [17]:
Y_predict_tree = tree_clf.predict(X_test)
cnfmatrix_tree = confusion_matrix(Y_test,Y_predict_tree)
print(cnfmatrix_tree)

[[14  0  0  0]
 [ 0  8  0  0]
 [ 0  0  9  0]
 [ 0  0  0  9]]


# * SGD

In [18]:
sgd_clf = SGDClassifier(max_iter=10, tol=.1)
sgd_clf.fit(X_train,Y_train)
print("The accurace of the SGD classifier is: {}".format( sgd_clf.score(X_test,Y_test) ) )
print("The coeeficients of the best fit are: {} and the intercept is:{} ".format( sgd_clf.coef_, sgd_clf.intercept_ ) )

The accurace of the SGD classifier is: 1.0
The coeeficients of the best fit are: [[ 1.51374353e+02  2.32113612e+02  9.72049624e+01 -5.12916245e+01
   1.16154721e+02  1.89319990e+02  1.64035207e+01 -1.15317195e+02
  -6.12628985e+01 -1.84415980e+02  3.22860840e+01 -1.45298363e+01
  -1.39330681e+01 -4.16304699e+01 -1.98328203e+01  2.72807251e+01]
 [-3.24857240e+02  3.01415507e+01 -5.31322805e+00  2.32019916e+02
  -1.57471910e+02 -1.19165513e+01  3.98150143e+01 -7.56349757e+00
  -1.14893530e+02 -9.13273532e+01 -7.57013806e+01  3.10043799e+02
  -1.64790977e+02  9.17835517e+00 -1.60390204e+02 -4.69697716e+01]
 [ 1.39678883e+02 -1.57166777e+02  2.97898550e+01  3.33514764e+01
   1.24681669e+01 -4.60722807e+02  8.59942075e+01  2.18492101e+02
   3.29396582e+01  1.28396569e+02 -6.06245318e-02 -4.59417737e+00
  -3.20887354e+01 -1.41522420e-01  1.28621356e+02 -1.20039942e+02]
 [-1.82840351e+02 -1.48709049e+02 -4.16213038e+01 -1.30561900e+02
  -9.03447476e+01  1.24398228e+02 -2.27637877e+01 -5.79589

Confusion matrix

In [19]:
Y_predict_sgd = sgd_clf.predict(X_test)
cnfmatrix_sgd = confusion_matrix(Y_test,Y_predict_tree)
print(cnfmatrix_sgd)

[[14  0  0  0]
 [ 0  8  0  0]
 [ 0  0  9  0]
 [ 0  0  0  9]]


# * Bayes

In [21]:
nb_clf = GaussianNB()
nb_clf.fit(X_train,Y_train)
print("The accuracy of the knn classifier is: {}".format( nb_clf.score(X_test,Y_test) ) )

The accuracy of the knn classifier is: 1.0


Confusion matrix

In [22]:
Y_predict_nb = nb_clf.predict(X_test)
cnfmatrix_nb = confusion_matrix(Y_test,Y_predict_tree)
print(cnfmatrix_nb)

[[14  0  0  0]
 [ 0  8  0  0]
 [ 0  0  9  0]
 [ 0  0  0  9]]
